app/app/urls.py
from cgitb import handler
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from core.views import Index,Register_user   
from django.contrib.auth.views import LoginView, logout_then_login
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/clearcache/', include('clearcache.urls')),
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('', include('sentiment_analysis.urls', namespace='sentiment_analysis')),
    path('', login_required(Index.as_view()), name = 'index'),
    path('accounts/login/', LoginView.as_view(template_name ='core/login.html'), name = 'login'),
    path('logout/', logout_then_login, name = 'logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = "core.views.handle_not_found"

app/sentiment_analysis/urls.py
from django.urls import path, re_path

from .views import audio_recorder, sentiment_analysis, audio_delete

app_name = 'sentiment_analysis'

urlpatterns = [
    path('record/', audio_recorder, name = 'audio_recorder'),
    #path('audio_analyze/', audio_recorder, name = 'audio_recorder'),
    re_path(r'^audio_analyze/$', sentiment_analysis, name='audio_analyze'),
    re_path(r'^audio_delete/$', audio_delete, name='audio_delete'),
]

app/templates/dom_components/layoutSidenav_content.html
<div id="layoutSidenav_content">
    <main>
        <!--Header-->
        <div class="header" style="background: url(/static/static/assets/img/prueba1/{{backgroundHeader}}.jpg); background-size: cover;">        
            <header class="row">
                <div class="title">
                    <h1 class="name">WHA <span>Health Analytics</span></h1>
                    <h3>Lorem ipsum dolor sit amet consectetur adipisicing elit.</h3><!--phrase of the company WHA-->
                </div>
            </header>
        </div>
        
        <!--About us-->
        <div class="container p-5">
            <div class="row">
                <div class="col col-xl-5 col-lg-5 m-auto col-md-12 col-sm-12 col-12">
                    <div class="crumina-module crumina-heading">
                        <h2 class="heading-title">Quienes somos</span></h2>
                        <p class="heading-text" style="text-align: justify;">Lorem ipsum dolor sit amet consectetur adipisicing
                            elit. Doloremque, minus possimus nam consequatur suscipit modi illo voluptates expedita,
                            reprehenderit recusandae rem accusantium veniam at distinctio amet quae hic harum sint.
                        </p>
        
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti veritatis qui corporis obcaecati
                            vel, cumque saepe, doloribus esse maxime dolor enim pariatur ab veniam quaerat aut, suscipit
                            necessitatibus labore quibusdam?</p>
        
                    </div>
                </div>
        
                <div class="col col-xl-7 col-lg-7 col-md-12 col-sm-12 col-12">
                    <img src="/static/static/assets/img/prueba1/11.jpg" class="w-100" alt="screen">
                </div>
            </div>
        </div>  
        <!--Carousel and strategic objectives-->        
        <div class="container p-5">
            <div class="row">
                <div class="col col-xl-9 col-lg-9 m-auto col-md-12 col-sm-12 col-12">
                    <div class="crumina-module crumina-heading">
                        <div id="slideshow" class="carousel slide" data-bs-ride="carousel">
                            <div class="carousel-inner">
                                <div class="carousel-item active">
                                    <p class="text-center"> <b>Publicitar a través de los diferentes medios y redes sociales el uso de las herramientas de AutoML y las ventajas que
                                    ofrecen su uso dentro de varios sectores industriales.</b></p>
                                    <img src="/static/static/assets/img/prueba1/strategicObjectives1.jpg" class="w-100" alt="">
        
                                </div>
                                <div class="carousel-item">
                                    <p class="text-center"><br><b>Soportar el desarrollo de la plataforma WHA desde un enfoque cloud híbrido privado y público.</b></p>
                                    <img src="/static/static/assets/img/prueba1/strategicObjectives2.jpg" class="w-100" alt="">
        
                                </div>
                                <div class="carousel-item">
                                    <p class="text-center"><b>Acrecentar la competitividad a través de la propuesta de algoritmos vanguardistas del estado del arte y la innovación de
                                    productos. </b></p>
                                    <img src="/static/static/assets/img/prueba1/strategicObjectives3.jpg" class="w-100" alt="">
                                </div>

                                <div class="carousel-item">
                                    <p class="text-center"><br><b>Implementar y mantener un modelo de gestión empresarial basado en un modelo de gestión de la calidad.</b></p>
                                    <img src="/static/static/assets/img/prueba1/strategicObjectives4.jpg" class="w-100" alt="">
                                </div>

                                <div class="carousel-item">
                                    <p class="text-center"><b>Captar clientes industriales de diferentes quehaceres que requieran soluciones de AutoML en los ámbitos de visión por
                                    computadora y procesamiento del lenguaje natural.</b></p>
                                    <img src="/static/static/assets/img/prueba1/strategicObjectives5.jpg" class="w-100" alt="">
                                </div>
                            </div>
        
                            <!--indicadores-->
                            <div class="carousel-indicators">
                                <button type="button" data-bs-target="#slideshow" data-bs-slide-to="0" class="active"
                                    aria-current="true" aria-label="Slide #1"></button>
        
                                <button type="button" data-bs-target="#slideshow" data-bs-slide-to="1" aria-current="true"
                                    aria-label="Slide #2"></button>
        
                                <button type="button" data-bs-target="#slideshow" data-bs-slide-to="2" aria-current="true"
                                    aria-label="Slide #3"></button>
                                
                                <button type="button" data-bs-target="#slideshow" data-bs-slide-to="3" aria-current="true"
                                    aria-label="Slide #4"></button>
                                
                                <button type="button" data-bs-target="#slideshow" data-bs-slide-to="4" aria-current="true"
                                    aria-label="Slide #5"></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--Mission-->       
        <div class="container p-5">
            <div class="row">
                <div class="col col-xl-7 col-lg-7 col-md-12 col-sm-12 col-12">
                    <img src="/static/static/assets/img/prueba1/mission.png" class="w-100" alt="screen">
                </div>
        
                <div class="col col-xl-5 col-lg-5 m-auto col-md-12 col-sm-12 col-12">
                    <div class="crumina-module crumina-heading">
                        <h2 class="heading-title text-center">Misión</h2>
                        <p class="heading-text" style="text-align: justify;">WHA es una empresa que se dedica a dar soluciones de AutoML (Machine Learning automatizado para predicción,
                        clasificación y regresión) en diversas aplicaciones industriales, a través del uso de técnicas de Visión por
                        Computadora, Procesamiento del Lenguaje Natural, Modelos clásicos de regresión y clasificación, matemáticas y
                        estadística entre otras, para facilitar la toma de decisiones estratégicas en la generación de valor, aumento de la
                        competitividad, descubrimiento de mercados, gestión del riesgo y gestión de la calidad.
                        </p>
        
                        <p>        
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <!--Vision-->        
        <div class="container p-5">
            <div class="row">
                <div class="col col-xl-5 col-lg-5 m-auto col-md-12 col-sm-12 col-12">
                    <div class="crumina-module crumina-heading">
                        <h2 class="heading-title text-center">Visión</h2>
                        <p class="heading-text" style="text-align: justify;">El horizonte temporal de WHA es bianual, por lo tanto, en el año 2026 WHA se consolidará como una compañía líder en el
                        mercado de soluciones de AutoML en las naciones de Colombia y España. Igualmente, será reconocida por sus contribuciones
                        en el desarrollo de las pequeñas y medianas empresas en diferentes sectores industriales, a través de la aplicación de
                        algoritmos vanguardistas que la industria demande. Además, su plataforma whacloud.com se convertirá en una herramienta
                        indispensable para la toma de decisiones gerenciales de nuestros clientes.
                        </p>
        
                        <p>        
                        </p>
                    </div>
                </div>
        
                <div class="col col-xl-7 col-lg-7 col-md-12 col-sm-12 col-12">
                    <img src="/static/static/assets/img/prueba1/vision.png" class="w-100" alt="screen">
                </div>
            </div>
        </div>
    </main>
    <!--Footer-->
    <footer class="py-4 bg-light mt-auto">
        <div class="container-fluid px-4">
            <div class="d-flex align-items-center justify-content-between small">
                <div class="text-muted">Copyright &copy; Your Website 2021</div>
                <div>
                    <a href="#">Privacy Policy</a>
                    &middot;
                    <a href="#">Terms &amp; Conditions</a>
                </div>
            </div>
        </div>
    </footer>
</div>

app/templates/dom_components/layoutSidenav_nav.html
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">Products</div>
                <a class="nav-link" href="{% url 'sentiment_analysis:audio_recorder' %}">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Sentiment analysis
                </a>
                <div class="sb-sidenav-menu-heading">Interface</div>
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    Interface 1
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="#">Option 1</a>
                        <a class="nav-link" href="#">Option 2</a>
                    </nav>
                </div>       
            </div>
        </div>
        <div class="sb-sidenav-footer">
            <div class="small">Logged in as:</div>
            User {{user.username}}
        </div>
    </nav>
</div>

app/templates/dom_components/nav.html
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-3" href="{% url 'index' %}">WHA Health Analytics</a>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
            <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#!">Settings</a></li>
                <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                <li><hr class="dropdown-divider" /></li>
                <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
            </ul>
        </li>
    </ul>
</nav>